#!/usr/bin/env bash
# ╔════════════════════════════════════════════════════╗
# │ Install – Instalador Post-Install de Ubuntu        │
# │ Versión: 4.0                                       │
# │ Autor: Daniel Calderon - Kapelu                    │
# │ Fecha: 19-02-2026                                  │
# │ WebSite: https://danielcalderon.vercel.app/        │
# │ Github: https://github.com/Kapelu                  │
# ╚════════════════════════════════════════════════════╝
set -Eeuo pipefail
IFS=$'\n\t'
clear

# Variables
# ------------------------------------------
LOG_FILE="$HOME/setup.log"
VERSION="3.0"
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
USUARIO=$(whoami)
HOSTNAME=$(hostname)
FECHA=$(date "+%d-%m-%Y")
HORA=$(date "+%H:%M:%S")
declare -A COLOR=(
  [reset]=$'\e[0m'
  [bold]=$'\e[1m'
  [italic]=$'\e[3m'

  [info]=$'\e[36m'
  [ok]=$'\e[32m'
  [warn]=$'\e[33m'
  [error]=$'\e[31m'

  [yellow]=$'\e[0;33m'
  [red]=$'\e[1;31m'
  [green]=$'\e[0;32m'
  [blue]=$'\e[34m'
  [magenta]=$'\e[35m'
  [gray]=$'\e[90m'
)

# Cargar scripts
source "$BASE_DIR/script/ui"
source "$BASE_DIR/script/log"
source "$BASE_DIR/script/update"
source "$BASE_DIR/script/helper"
source "$BASE_DIR/script/os_info"


source "$BASE_DIR/script/config.sh"
source "$BASE_DIR/script/node.sh"
source "$BASE_DIR/script/vscode.sh"
source "$BASE_DIR/script/firefox_remove.sh"
source "$BASE_DIR/script/brave.sh"
source "$BASE_DIR/script/google.sh"
source "$BASE_DIR/script/protonvpn.sh"
source "$BASE_DIR/script/sublime.sh"

# Redirección silenciosa (todo al log excepto mensajes visibles)
# Crea $HOME/setup.log - Header controlado
LAST_LINE="$(tail -n 1 "$LOG_FILE" 2>/dev/null || true)"
NEW_HEADER="===== START -> Install $(date '+%Y-%m-%d %H:%M:%S') ====="

# Solo agrega si no es igual al último
if [[ "$LAST_LINE" != "$NEW_HEADER" ]]; then
  echo "" >> "$LOG_FILE"
  echo "$NEW_HEADER" >> "$LOG_FILE"
fi

# Redirección
exec 3>&1
exec 1>>"$LOG_FILE" 2>&1


# Función para mostrar mensajes en pantalla
# ------------------------------------------
main() {
  START=$SECONDS
  clear
  logo
	echo ""
  print_banner " 🚀 Iniciando Secuencia Post-Install..."
	echo ""

  update
	install_apt
	install_snap


  config

  install_vscode
  remove_firefox
  install_brave
  install_google
  install_protonvpn
  install_sublime

  cleanup
	clear
	os_info


  ELAPSED=$(( SECONDS - START ))
  HORAS=$((ELAPSED / 3600))
  MINUTOS=$(( (ELAPSED % 3600) / 60 ))
  SEGUNDOS=$((ELAPSED % 60))

  FECHA=$(date '+%Y-%m-%d')
  HORA=$(date '+%H:%M:%S')

  clear
  print_banner "  🎉 Secuencia Post-Install completada con éxito!!!
	Usuario: $USUARIO
	Host: $HOSTNAME
	Fecha: $FECHA
	Hora de inicio: $HORA
	Hora de fin   : $(date '+%H:%M:%S')
	Tiempo total  : ${HORAS}h:${MINUTOS}m:${SEGUNDOS}s"
}

main "$@"