#!/usr/bin/env bash
# ╔════════════════════════════════════════════════════╗
# │ Install – Instalador Post-Install de Ubuntu        │
# │ Versión: 4.0                                       │
# │ Autor: Daniel Calderon - Kapelu                    │
# │ Fecha: 19-02-2026                                  │
# │ WebSite: https://danielcalderon.vercel.app/        │
# │ Github: https://github.com/Kapelu                  │
# ╚════════════════════════════════════════════════════╝
set -Eeuo pipefail
IFS=$'\n\t'
clear
# Protección: evitar ejecución fuera de kapelu
[[ $EUID -ne 0 ]] && { echo "Debe ejecutarse como root"; exit 1; }

# Variables
# ------------------------------------------
LOG_FILE="$HOME/setup.log"
VERSION="3.0"
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
USUARIO=$(whoami)
HOSTNAME=$(hostname)
FECHA=$(date "+%d-%m-%Y")
HORA=$(date "+%H:%M:%S")
declare -A COLOR=(
  [reset]=$'\e[0m'      # Reset / color normal
  [bold]=$'\e[1m'       # Negrita
  [italic]=$'\e[3m'     # Cursiva (no siempre soportado)
  
  [error]=$'\e[31m'     # Rojo
  [ok]=$'\e[32m'        # Verde
  [warn]=$'\e[33m'      # Amarillo
  [info]=$'\e[34m'      # Azul
	
  [magenta]=$'\e[35m'   # Magenta / violeta
	[cyan]=$'\e[36m'      # Cyan
  [gray]=$'\e[90m'      # Gris oscuro / gris claro dependiendo de la terminal
)

# Directorio base donde se encuentran los scripts
BASE_SCRIPT="${BASE_SCRIPT:-$(dirname "$(realpath "$0")")}"

# Array con todos los scripts a cargar
SCRIPTS=(
  "ui"
  "log"
  "update"
  "helper"
  "os_info"
  "remove_firefox"
  "brave"
  "vscode"
  "google"
)

# Cargar todos los scripts en una sola línea de ejecución
for script in "${SCRIPTS[@]}"; do
    source "$BASE_SCRIPT/script/$script"
done

# Mensaje de confirmación
echo "Todos los scripts se han cargado correctamente."

# Redirección silenciosa (todo al log excepto mensajes visibles)
# Crea $HOME/setup.log - Header controlado
LAST_LINE="$(tail -n 1 "$LOG_FILE" 2>/dev/null || true)"
NEW_HEADER="===== START -> Install $(date '+%Y-%m-%d %H:%M:%S') ====="

# Solo agrega si no es igual al último
if [[ "$LAST_LINE" != "$NEW_HEADER" ]]; then
  echo "" >> "$LOG_FILE"
  echo "$NEW_HEADER" >> "$LOG_FILE"
fi

# Redirección
exec 3>&1
exec 1>>"$LOG_FILE" 2>&1


# Función para mostrar mensajes en pantalla
# ------------------------------------------
main() {
  START=$SECONDS
  clear
  logo
	echo ""
  print_banner " 🚀 Iniciando Secuencia Post-Install..."
	echo ""

  update
	install_apt
	install_snap
	remove_firefox
	brave
	google
	vscode
	sublime

	update
	clear
	os_info
  cleanup
	
	ELAPSED=$(( SECONDS - START ))
  HORAS=$((ELAPSED / 3600))
  MINUTOS=$(( (ELAPSED % 3600) / 60 ))
  SEGUNDOS=$((ELAPSED % 60))

  FECHA=$(date '+%Y-%m-%d')
  HORA=$(date '+%H:%M:%S')

  clear
  print_banner "  🎉 Secuencia Post-Install completada con éxito!!!
	Usuario: $USUARIO
	Host: $HOSTNAME
	Fecha: $FECHA
	Hora de inicio: $HORA
	Hora de fin   : $(date '+%H:%M:%S')
	Tiempo total  : ${HORAS}h:${MINUTOS}m:${SEGUNDOS}s"
}

main "$@"