#!/usr/bin/env bash
# ╔════════════════════════════════════════════════════╗
# │ Autor: Daniel Calderon - Kapelu                    │
# │ Fecha: XX/XX/XXXX                                  │
# │ WebSite: https://danielcalderon.vercel.app/        │
# │ Github: https://github.com/Kapelu                  │
# ╚════════════════════════════════════════════════════╝
set -Eeuo pipefail
IFS=$'\n\t'
clear

source "$BASE_DIR/script/install_apt"
source "$BASE_DIR/script/install_snap"

install_snap() {
  log_info "📦 Instalando herramientas snap..."
  install_snap "${SNAP_TOOLS[@]}"
}

install_apt(){
	log_info "📦 Instalando paquetes apt..."
  install_apt "${APT_TOOLS[@]}"
}

