#!/usr/bin/env bash
# ╔════════════════════════════════════════════════════╗
# │ Nombre – Descripción                               │
# │ Versión: X.X                                       │
# │ Autor: Daniel Calderon - Kapelu                    │
# │ Fecha: XX/XX/XXXX                                  │
# │ WebSite: https://danielcalderon.vercel.app/        │
# │ Github: https://github.com/Kapelu                  │
# ╚════════════════════════════════════════════════════╝
set -Eeuo pipefail
IFS=$'\n\t'
clear

APT_TOOLS=( 
  wget 
  gpg 
  apt-transport-https 
  chrome-gnome-shell 
  gnome-browser-connector 
  font-manager 
  net-tools
  lsd
  dialog
  build-essential
  )

# Config
# ------------------------------
RETRIES=3
DEBIAN_FRONTEND=noninteractive

retry() {
  local n=1
  local max=$RETRIES
  local delay=2

  while true; do
    "$@" && break || {
      if (( n < max )); then
        log "⚠️ Reintento $n/$max: $*"
        ((n++))
        sleep $delay
      else
        error_exit "$*"
      fi
    }
  done
}

is_installed() {
  dpkg -s "$1" &>/dev/null
}

install_apt() {
  local to_install=()

  for arg in "$@"; do
    [[ "$arg" == -* ]] && continue

    local pkg="$arg"
    pkg="${pkg%%=*}"
    pkg="${pkg%%:*}"

    if is_installed "$pkg"; then
      log "✔ $arg ya está instalado"
    else
      to_install+=("$arg")
    fi
  done

  if [ ${#to_install[@]} -eq 0 ]; then
    log "✔ Nada para instalar"
    return 0
  fi

  log "📦 Instalando: ${to_install[*]}"
  retry sudo apt-get install -y "${to_install[@]}"
}