#!/bin/bash
sudo apt install apt-transport-https &&
sudo apt update &&
sudo apt install code # or code-insiders


echo "⬆️ Asegurando última versión..."
sudo apt update -y
sudo apt install --fix-missing -y
sudo apt upgrade --allow-downgrades -y
sudo apt full-upgrade --allow-downgrades -y
echo ""
echo ""
sleep 3

echo " LIMPIANDO SISTEMA..."
sudo apt install -f
sudo apt autoremove -y
sudo apt autoclean -y
sudo apt clean
echo ""
echo ""
sleep 3

clear